version: '3'
services:
  # Service for managing books
  books-service:
    build:
      context: ./services/books
    ports:
      - '8081:8080'
    environment:
      - MONGO_URI=mongodb://mongo:27017/books
  # Service for managing users
  users-service:
    build:
      context: ./services/users
    ports:
      - '8082:8080'
    environment:
      - MONGO_URI=mongodb://mongo:27017/users
  # Service for managing borrowing activities
  borrowing-service:
    build:
      context: ./services/borrowing
    ports:
      - '8083:8080'
    environment:
      - MONGO_URI=mongodb://mongo:27017/borrowing
  # MongoDB database service
  mongo:
    image: mongo
    ports:
      - '27017:27017'