version: '3'
services:
  # Dịch vụ quản lý sách
  books-service:
    build:
      context: ./services/books
    ports:
      - '8081:8080'
    environment:
      - MONGO_URI=mongodb://mongo:27017/books  # MongoDB URI for books service
  # Dịch vụ quản lý người dùng
  users-service:
    build:
      context: ./services/users
    ports:
      - '8082:8080'
    environment:
      - MONGO_URI=mongodb://mongo:27017/users  # MongoDB URI for users service
  # Dịch vụ quản lý hoạt động mượn sách
  borrowing-service:
    build:
      context: ./services/borrowing
    ports:
      - '8083:8080'
    environment:
      - MONGO_URI=mongodb://mongo:27017/borrowing  # MongoDB URI for borrowing service
  # Dịch vụ cơ sở dữ liệu MongoDB (phiên bản được chỉ định)
  mongo:
    image: mongo:5.0  # Specify image version for stability
    ports:
      - '27017:27017'  # Exposing MongoDB port

# Tệp docker-compose này xác định nhiều microservices và một cơ sở dữ liệu MongoDB.